---
title: "Hands-on Exercise 00: Working with tidyverse"
author: "Dr. Kam Tin Seong"
date-modified: "last-modified"
execute:
  echo: true
  eval: true
  warning: false
  freeze: true
---

## Getting started

Loading tidyverse onto r environment by using the code chunk below.

```{r}
pacman::p_load(tidyverse)
```

## Importing data

Code chunk below uses read_csv() of readr to import REALIS2019.csv into r environment as a tibble data.frame.

```{r}
realis2019 <- read_csv("data/REALIS2019.csv")
```

```{r}
#| eval: FALSE
popdata_fat <- read_csv("data/PopData2019_fat.csv")
```

## Pivoting data

```{r}
#| eval: FALSE
popdata_long <- popdata_fat %>%
  pivot_longer(c(3:21),
               names_to = "Age Group",
               values_to = "Population")
```

```{r}
#| eval: FALSE
write_rds(popdata_long, "rds/popdata_long.rds")
```


```{r}
#| echo: FALSE
popdata_long <- read_rds("rds/popdata_long.rds")
```


## Working with dplyr

```{r}
realis2019_selected <- realis2019 %>%
  select(`Project Name`,
         `Transacted Price ($)`,
         `Type of Sale`,
         `Unit Price ($ psm)`, 
         `Property Type`)
realis2019_selected
```

### Working with filter() of dplyr.

```{r}
realis2019_filtered <- realis2019_selected %>%
  filter(`Property Type` =="Condominium" |
           `Property Type`== "Apartment") %>%
  filter(`Type of Sale` == "New Sale") %>%
  filter(`Unit Price ($ psm)` <= 13000)
```

### Putting all together

```{r}
realis2019_end <- realis2019 %>%
  select(`Project Name`,
         `Transacted Price ($)`,
         `Type of Sale`,
         `Unit Price ($ psm)`, 
         `Property Type`) %>%
  filter(`Property Type` =="Condominium" |
           `Property Type`== "Apartment") %>%
  filter(`Type of Sale` == "New Sale") %>%
  filter(`Unit Price ($ psm)` <= 13000)
```



